TEST_NAME = (
    "[test]\n"
    "ID = {x}\n"
    "name = {test_name}\n"
    "description = {test_name} test file\n"
    "log_file = {test_name}.log\n"
    "\n"
)
GENERATE_CFG = (
    "/////////////////////////////////////////////////////////////////////\n"
    "// Generate cfg files for load (called from load before kickstart)\n"
    "/////////////////////////////////////////////////////////////////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device = CS49834Console\n"
    "command = working_folder\n"
    "value = Globals::D_duet_tools\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = show_window\n"
    "value = 0\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = Make remap cfg files\n"
    "device = CS49834Console\n"
    "command = command\n"
    "value = duet_lib.py \"{cmd_params}\"\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = Make cfg files\n"
    "device = CS49834Console\n"
    "command = command\n"
    "value = datmos_ht_exec.exe -if {stream_path}.mlp {cmd_params}\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = Copy cfg files\n"
    "device = CS49834Console\n"
    "command = command\n"
    "value = copy_cfgs.bat {test_path}\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
MAT_CBR_ON = (
    "//////////////////////////////////////////////////matify truehd stream/////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_4\n"
    "command = value\n"
    "value = copy /y \n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_4\n"
    "command = concat\n"
    "value = Globals::D_duet_streams\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_4\n"
    "command = concat\n"
    "value = {stream_path} \n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value =  StringManager_4::value\n"
    "delay = 2000\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = MAT_CBR.exe -i{play_file}.mat -o{play_file}.iec \n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = matenc_off.bat \n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {play_file}.iec \n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {play_file}.iec\n"
    "delay = 0\n"
    "option = [SET]\n"
    " \n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
)
MAT_CBR_OFF = (
    "//////////////////////////////////////////////////matify truehd stream/////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = matenc_off.bat \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = Globals::D_duet_streams\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {stream_path} \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {play_file}.mat\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
MAT_CBR_OFF_MLP = (
    "//////////////////////////////////////////////////matify truehd stream/////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = matenc.bat \n"
    "delay = 0\n"
    "option = [SET]\n"""
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = Globals::D_duet_streams\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {stream_path} \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {play_file}.mat\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
PATH_TO_OUTPUT = (
    "///////////////////////////////////////////////////////////\n"
    "// Set up path to asio output file\n"
    "///////////////////////////////////////////////////////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_3\n"
    "command = value\n"
    "value = Globals::D_duet_tools\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_3\n"
    "command = concat\n"
    "value = out_dut_sync.wav\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
RENAME_DUT_TO_REF = (
    "/////////////////////////////////////////////////////////////////\n"
    "// Rename out_dut.wav to out_ref.wav if there is no out_ref.wav\n"
    "/////////////////////////////////////////////////////////////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device = CS49834Console\n"
    "command = working_folder\n"
    "value = Globals::D_duet_tools\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_8\n"
    "command = value\n"
    "value = rename_dut_to_ref.bat \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_8\n"
    "command = concat\n"
    "value = Globals::D_duet_output\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager_8\n"
    "command = concat\n"
    "value = {test_folder}\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager_8::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
MERGE = (
    "/////////////////////////////////////////////////\n"
    "// Merge iteration outputs\n"
    "/////////////////////////////////////////////////\n"
    "\n"
    "[step]\n"
    "description = Working folder where are placed recorded duts\n"
    "device = CS49834Console\n"
    "command = working_folder\n"
    "value = Globals::D_duet_tools\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = Call of oar_wavmerge.exe\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = oar_wavmerge -s0xbadace00 \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = Take location of reference stream\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = Globals::D_duet_output\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {test_folder}out_ref.wav out_dut.wav out_dut_sync.wav\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = execute merging of duts\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value =  StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
MOVE_DUT = (
    "/////////////////////////////////////////////////\n"
    "// Move dut to output folder\n"
    "/////////////////////////////////////////////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = move /y out_dut.wav \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = Globals::D_duet_output\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {test_folder}{out_file_name}\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
DEL_STREAM = (
    "////////////////////////////////////////////////////////////////\n"
    "// del matified truehd stream\n"
    "////////////////////////////////////////////////////////////////\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = value\n"
    "value = del /Q \n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = Globals::D_duet_tools\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  StringManager\n"
    "command = concat\n"
    "value = {play_file}.mat out_dut_sync.wav *.cfg\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = StringManager::value\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description = Working folder in Tools\n"
    "device =  CS49834Console\n"
    "command = working_folder\n"
    "value = Globals::D_duet_tools\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
    "[step]\n"
    "description =\n"
    "device =  CS49834Console\n"
    "command = command\n"
    "value = kill_asio.bat\n"
    "delay = 0\n"
    "option = [SET]\n"
    "\n"
)
